#!/usr/bin/env bash

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/tmux-sessioniser"
CONFIG_FILE="$CONFIG_DIR/tmux-sessioniser.conf"

TS_SEARCH_PATHS=(~/workplace)
TS_MAX_DEPTH=3

[[ -f "$CONFIG_FILE" ]] && source "$CONFIG_FILE"

find_dirs() {
    zoxide query --list 2>/dev/null

    for entry in "${TS_SEARCH_PATHS[@]}"; do
        if [[ "$entry" =~ ^([^:]+):([0-9]+)$ ]]; then
            path="${BASH_REMATCH[1]}"
            depth="${BASH_REMATCH[2]}"
        else
            path="$entry"
            depth="$TS_MAX_DEPTH"
        fi

        [[ -d "$path" ]] && fd . "$path" --type d --max-depth "$depth"
    done
}

has_session() {
    tmux has-session -t "$1" 2>/dev/null
}

switch_to() {
    if [[ -z $TMUX ]]; then
        tmux attach-session -t "$1"
    else
        tmux switch-client -t "$1"
    fi
}

selected="$(
  find_dirs \
    | awk '!seen[$0]++ {
        full=$0

        # strip trailing slash
        gsub(/\/$/, "", full)

        # basename = directory name
        n=split(full, arr, "/")
        name=arr[n]

        printf "%s\t%s\n", full, name
      }' \
    | fzf \
        --height 100% \
        --layout=reverse \
        --border \
        --prompt="session> " \
        --with-nth=2 \
        --delimiter=$'\t' \
        --preview 'eza --tree --icons --level=2 {1}' \
        --preview-window=right:70%
)"

[[ -z "$selected" ]] && exit 0

selected_path="${selected%%$'\t'*}"
default_name=$(basename "${selected%%$'\t'*}" | tr '. ' '__')

read -rp "Session name [$default_name]: " selected_name
selected_name=${selected_name:-$default_name}

tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s "$selected_name" -c "$selected_path"
    exit 0
fi

if ! has_session "$selected_name"; then
    tmux new-session -ds "$selected_name" -c "$selected_path"
fi

switch_to "$selected_name"
