# === Basics ===

unbind C-b
set -g prefix C-a

bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -s escape-time 0 # Removes delay after pressing Esc

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

set -g history-limit 10000

set -g mouse on

set -g focus-events on

bind -r x kill-pane

set -g set-clipboard on

set -g pane-border-lines double

# === Navigation ===

bind -r \\ split-window -h -c "#{pane_current_path}" # need to \ to use \ key in config
bind -r - split-window -v -c "#{pane_current_path}"
bind -r c new-window -c "#{pane_current_path}"

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# Pane resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind -r n next-window
bind -r p previous-window

# Swap window numbers with < and >
bind -r < swap-window -t -1\; select-window -t -1
bind -r > swap-window -t +1\; select-window -t +1

setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

bind S command-prompt -p "new session:" "new-session -s '%%'"

# === Plugins ===

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-cpu'

# === Theme ===

set -g @catppuccin_flavor "latte"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_text "#W"
set -g @catppuccin_window_current_text "#W"

# Auto-switch with macOS dark mode (tmux 3.6+)
set-hook -g client-dark-theme {
    set -g @catppuccin_flavor "mocha"
    set -g @catppuccin_reset "true"
    run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
}
set-hook -g client-light-theme {
    set -g @catppuccin_flavor "latte"
    set -g @catppuccin_reset "true"
    run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
}

# Load catppuccin
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# Status bar
set -g status-position top
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right ""
set -ag status-right "#{E:@catppuccin_status_directory}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -agF status-right "#{E:@catppuccin_status_ram}"
set -ag status-right "#{E:@catppuccin_status_session}"
# set -ag status-right "#{E:@catppuccin_status_user}"

# # OS icon at the far right
# if-shell "uname | grep -q Darwin" \
#   "set -ag status-right ''" \
#   "set -ag status-right ''"

# Load plugins (after catppuccin)
run ~/.config/tmux/plugins/tmux-cpu/cpu.tmux
run ~/.config/tmux/plugins/tpm/tpm
